// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMbwEDtertZmobgUhSEo1bwEWQ5BwEE48',
    appId: '1:115183806146:web:6613fb6abfbd703c9dbd5b',
    messagingSenderId: '115183806146',
    projectId: 'triton-37ec3',
    authDomain: 'triton-37ec3.firebaseapp.com',
    databaseURL: 'https://triton-37ec3-default-rtdb.firebaseio.com',
    storageBucket: 'triton-37ec3.appspot.com',
    measurementId: 'G-NTV9GXG960',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-UTCksZCe_j8ccQC0Dy92mVYL69ePLMU',
    appId: '1:115183806146:android:abe8ffa2b2b3f99c9dbd5b',
    messagingSenderId: '115183806146',
    projectId: 'triton-37ec3',
    databaseURL: 'https://triton-37ec3-default-rtdb.firebaseio.com',
    storageBucket: 'triton-37ec3.appspot.com',
  );
}
